#######################################################################################
#
#       Welcome to Riot Polls configuration, This is where you can change
#       Basic settings that will affect how the plugin preforms.
#       This plugin does have database support; see 'Storage' for more information.
#
#######################################################################################

Storage:
  # Visit 'Plugins/RiotTeleportation/Lang/' to see the supported languages.
  Language File: "en_US"
  # Name of Lobby server
  lobby: "lobby"

Teleportation-Ask:
  require-payment: true
  cost: 15.0
  # !! Days - d | Hours - h | Minutes - m | Seconds - s
  cooldown: "5m"
  teleport-delay: 5
  request-timeout: 120
  success:
    has-chat-message: true
    has-title: true
    title-content: "&aTeleportation Success!"
    subtitle-content: "&eTeleported to %player%"

Teleportation-Random:
  require-payment: true
  cost: 150.0
  # !! Days - d | Hours - h | Minutes - m | Seconds - s
  cooldown: "5m"
  teleport-delay: 5
  world-border:
    enable-limit: true
    range: 10000
  success:
    has-chat-message: true
    has-title: true
    title-content: "&aTeleportation Success!"
    subtitle-content: "&eTeleported to random location"
